apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-container-back
  template:
    metadata:
      labels:
        app: deployment-container-back
    spec:
      containers:
      - name: deployment-container-back
        image: imagem-container-back:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "40m"
            memory: "64Mi"
          requests:
            cpu: "20m"
            memory: "32Mi"
